"""The front panel's wire vocabulary: role codes and status glyphs (PANEL-V017).

GENERATED by tools/gen_panel_codes.py from design/tokens.json (panel.roles, grammar) and the
panel's glyph table (tools/clcd_mock.py GLYPHS): do not edit. Change the source, then run:
python3 tools/gen_panel_codes.py.

A frame's role code for ``ROLES[i]`` is ``chr(ord("a") + i)`` (net-protocol v0.17); a
glyph is the character ``chr(code)``. ``harness_manager.core.panel`` decodes with these;
the web UI's ``js/panel_codes.js`` holds the same, from the same generator.
"""

TOKENS_SHA256 = "59011d724e13ec07902e37ffdd3f6a480394cc0995d42649b3af320a73c4a4bb"
#: The panel's theme in the tokens (the colours below are that theme's).
PANEL_THEME = "dark"

#: The colour roles, in design/tokens.json order (= clcd_palette.h's enum clcd_role).
ROLES: tuple[str, ...] = (
    "text",
    "label",
    "value",
    "rule",
    "chrome",
    "title",
    "title-held",
    "title-warn",
    "ok",
    "warn",
    "err",
    "busy",
    "unk",
    "held",
    "bar",
    "track",
    "banner-err",
    "banner-warn",
    "banner-ok",
    "banner-busy",
    "banner-held",
)

#: role -> (fg, bg) as the glass shows them (RGB565, expanded).
ROLE_COLOURS: dict[str, tuple[str, str]] = {
    "text": ("#e7e7ef", "#000000"),
    "label": ("#7b8694", "#000000"),
    "value": ("#e7e7ef", "#000000"),
    "rule": ("#313c4a", "#000000"),
    "chrome": ("#adb2bd", "#182029"),
    "title": ("#e7e7ef", "#182029"),
    "title-held": ("#b59ef7", "#182029"),
    "title-warn": ("#e7ae5a", "#182029"),
    "ok": ("#5ac78c", "#000000"),
    "warn": ("#e7ae5a", "#000000"),
    "err": ("#ef8a84", "#000000"),
    "busy": ("#7b9ef7", "#000000"),
    "unk": ("#cec39c", "#000000"),
    "held": ("#b59ef7", "#000000"),
    "bar": ("#000000", "#7b9ef7"),
    "track": ("#7b8694", "#182029"),
    "banner-err": ("#ffffff", "#b52421"),
    "banner-warn": ("#ffffff", "#945900"),
    "banner-ok": ("#ffffff", "#18794a"),
    "banner-busy": ("#ffffff", "#3159d6"),
    "banner-held": ("#ffffff", "#6b41c6"),
}

#: The status glyphs: code -> (name, 16 scanlines with bit 7 the leftmost pixel,
#: a one-column stand-in for a terminal).
GLYPHS: dict[int, tuple[str, tuple[int, ...], str]] = {
    0x80: ("ok", (0x00, 0x00, 0x00, 0x00, 0x02, 0x06, 0x04, 0x8C, 0xD8, 0x70, 0x20, 0x00, 0x00, 0x00, 0x00, 0x00), "*"),
    0x81: ("err", (0x00, 0x00, 0x00, 0x00, 0xC6, 0xEE, 0x7C, 0x38, 0x7C, 0xEE, 0xC6, 0x00, 0x00, 0x00, 0x00, 0x00), "X"),
    0x82: ("warn", (0x00, 0x00, 0x10, 0x38, 0x28, 0x6C, 0x54, 0xD6, 0x92, 0x82, 0x92, 0xFE, 0x00, 0x00, 0x00, 0x00), "!"),
    0x83: ("held", (0x00, 0x00, 0x38, 0x44, 0x44, 0x44, 0xFE, 0xFE, 0xEE, 0xEE, 0xFE, 0xFE, 0x00, 0x00, 0x00, 0x00), "#"),
    0x84: ("user", (0x00, 0x00, 0x38, 0x7C, 0x7C, 0x7C, 0x38, 0x00, 0x7C, 0xFE, 0xFE, 0xFE, 0x00, 0x00, 0x00, 0x00), "@"),
    0x85: ("unk", (0x00, 0x00, 0x38, 0x44, 0x04, 0x08, 0x10, 0x10, 0x00, 0x10, 0x10, 0x00, 0x00, 0x00, 0x00, 0x00), "?"),
    0x86: ("dot", (0x00, 0x00, 0x00, 0x00, 0x00, 0x38, 0x7C, 0x7C, 0x7C, 0x38, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00), "*"),
}
