"""The MPS3 board-pin model and the built-in designs the XDC export offers.

``mps3_board_pins.json`` is GENERATED by ``tools/gen_mps3_pins.py`` from the platform
repo (the fielded static's branch) and the Xilinx package file. It is a DERIVED
stand-in for harness Lane C's ``board_pins.yaml``, labelled as such in its ``status``
block; every fact names its source file and commit. Never edit it by hand.

The board-agnostic XDC service (``harness_manager.services.xdc``) finds a pack's pin
data by importing ``<pack package>.pins`` and calling ``load_model()`` and
``design_files()``: this module is that hook for the MPS3 pack.
"""

from __future__ import annotations

import functools
import json
from pathlib import Path
from typing import Any

HERE = Path(__file__).resolve().parent
MODEL_FILE = HERE / "mps3_board_pins.json"
DESIGNS_DIR = HERE / "designs"


@functools.lru_cache(maxsize=1)
def _load() -> str:
    return MODEL_FILE.read_text(encoding="utf-8")


def load_model() -> dict[str, Any]:
    """A fresh copy of the pin model (callers may annotate it)."""
    return json.loads(_load())


def design_files() -> dict[str, Path]:
    """Built-in designs, by name: ``{"nanosoc": Path(...)}``."""
    return {p.stem: p for p in sorted(DESIGNS_DIR.glob("*.json"))}
