// nanosoc_wrapper_skeleton.sv -- every partition port of static 0x44EE76D5.
// Generated by Harness Manager (xdc export). Groups this design does not use are
// tied to the value the shell's decoupler holds them at during a swap.
`timescale 1ns / 1ps

module rm_nanosoc #(parameter int NGPIO = 16) (
  input  logic              dut_clk,
  input  logic              dut_resetn,
  input  logic              rp_resetn,
  input  logic              dbg_resetn,
  input  logic              jtag_tck,
  input  logic              jtag_tms,
  input  logic              jtag_tdi,
  output logic              jtag_tdo,
  input  logic              dbg_bscan_bscanid_en,
  input  logic              dbg_bscan_capture,
  input  logic              dbg_bscan_drck,
  input  logic              dbg_bscan_reset,
  input  logic              dbg_bscan_runtest,
  input  logic              dbg_bscan_sel,
  input  logic              dbg_bscan_shift,
  input  logic              dbg_bscan_tck,
  input  logic              dbg_bscan_tdi,
  input  logic              dbg_bscan_tms,
  input  logic              dbg_bscan_update,
  output logic              dbg_bscan_tdo,
  input  logic              phy_rmii_ref_clk,
  input  logic              phy_rmii_crs_dv,
  input  logic [1:0]        phy_rmii_rxd,
  output logic [1:0]        phy_rmii_txd,
  output logic              phy_rmii_tx_en,
  output logic              mdc,
  output logic              mdio_o,
  output logic              mdio_oe,
  input  logic              mdio_i,
  output logic [7:0]        uart_tx_tdata,
  output logic              uart_tx_tvalid,
  input  logic              uart_tx_tready,
  input  logic [7:0]        uart_rx_tdata,
  input  logic              uart_rx_tvalid,
  output logic              uart_rx_tready,
  output logic              swo,
  output logic [31:0]       rm_id,
  output logic              dut_lockup,
  output logic              irq_out,
  output logic [NGPIO-1:0]  dut_gpio_o,
  output logic [NGPIO-1:0]  dut_gpio_oe,
  input  logic [NGPIO-1:0]  dut_gpio_i,
  output logic              qspi_sclk,
  output logic              qspi_csn,
  output logic [3:0]        qspi_io_o,
  output logic [3:0]        qspi_io_oe,
  input  logic [3:0]        qspi_io_i
);

  // jtag: used by this design: drive these
  // assign jtag_tdo = ...;
  // dbgbscan: not used: tied to the decoupler's safe-idle value
  assign dbg_bscan_tdo = 1'b0;
  // eth: not used: tied to the decoupler's safe-idle value
  assign phy_rmii_txd = '0;
  assign phy_rmii_tx_en = 1'b0;
  assign mdc = 1'b0;
  assign mdio_o = 1'b0;
  assign mdio_oe = 1'b0;
  // uart: used by this design: drive these
  // assign uart_tx_tdata = ...;
  // assign uart_tx_tvalid = ...;
  // assign uart_rx_tready = ...;
  // assign swo = ...;
  // status: used by this design: drive these
  assign rm_id = 32'h01000001;  // this RM's identity (the overlay manifest's rm_id)
  // assign dut_lockup = ...;
  // assign irq_out = ...;
  // gpio: used by this design: drive these
  // assign dut_gpio_o = ...;
  // assign dut_gpio_oe = ...;
  // qspi: used by this design: drive these
  // assign qspi_sclk = ...;
  // assign qspi_csn = ...;
  // assign qspi_io_o = ...;
  // assign qspi_io_oe = ...;

endmodule
