##############################################################################
# blinky_pins.xdc -- package pins (xcku115-flvb1760-1-c)
# design: blinky (a whole-FPGA blinky: the 50 MHz board clock, a reset button, 8 LEDs, 8 switches)
# board:  Arm V2M-MPS3 (HBI0309C), Kintex UltraScale KU115, part xcku115-flvb1760-1-c
# model:  DERIVED (harness Lane C's board_pins.yaml does not exist yet)
#         tools/gen_mps3_pins.py from feat/rm-ila-mint @ e54363022f
# Generated by Harness Manager (xdc export). Regenerate rather than edit: the
# checks that passed are listed in manifest.json next to this file.
# WHOLE-FPGA design: this replaces the harness shell on the board. For a design
# that loads into the shell's partition, use the RM kit instead.
##############################################################################

set_property PACKAGE_PIN AK16  [get_ports clk] ;# OSCCLK[1], bank 66, hw-proven
set_property PACKAGE_PIN AT30  [get_ports rst_n] ;# USER_nPB[0], bank 44, hw-proven
set_property PACKAGE_PIN AR30  [get_ports {led_n[7]}] ;# USER_nLED[7], bank 44, hw-proven
set_property PACKAGE_PIN AW31  [get_ports {led_n[6]}] ;# USER_nLED[6], bank 44, hw-proven
set_property PACKAGE_PIN AW30  [get_ports {led_n[5]}] ;# USER_nLED[5], bank 44, hw-proven
set_property PACKAGE_PIN AT33  [get_ports {led_n[4]}] ;# USER_nLED[4], bank 44, hw-proven
set_property PACKAGE_PIN AR32  [get_ports {led_n[3]}] ;# USER_nLED[3], bank 44, hw-proven
set_property PACKAGE_PIN AU31  [get_ports {led_n[2]}] ;# USER_nLED[2], bank 44, hw-proven
set_property PACKAGE_PIN AU30  [get_ports {led_n[1]}] ;# USER_nLED[1], bank 44, hw-proven
set_property PACKAGE_PIN AU32  [get_ports {led_n[0]}] ;# USER_nLED[0], bank 44, hw-proven
set_property PACKAGE_PIN AY31  [get_ports {sw[7]}] ;# USER_SW[7], bank 44, hw-proven
set_property PACKAGE_PIN AY33  [get_ports {sw[6]}] ;# USER_SW[6], bank 44, hw-proven
set_property PACKAGE_PIN BB30  [get_ports {sw[5]}] ;# USER_SW[5], bank 44, hw-proven
set_property PACKAGE_PIN BA30  [get_ports {sw[4]}] ;# USER_SW[4], bank 44, hw-proven
set_property PACKAGE_PIN BA33  [get_ports {sw[3]}] ;# USER_SW[3], bank 44, hw-proven
set_property PACKAGE_PIN BA32  [get_ports {sw[2]}] ;# USER_SW[2], bank 44, hw-proven
set_property PACKAGE_PIN BB29  [get_ports {sw[1]}] ;# USER_SW[1], bank 44, hw-proven
set_property PACKAGE_PIN BA29  [get_ports {sw[0]}] ;# USER_SW[0], bank 44, hw-proven
