##############################################################################
# blinky_io.xdc -- IO standards and pad properties, by bank
# design: blinky (a whole-FPGA blinky: the 50 MHz board clock, a reset button, 8 LEDs, 8 switches)
# board:  Arm V2M-MPS3 (HBI0309C), Kintex UltraScale KU115, part xcku115-flvb1760-1-c
# model:  DERIVED (harness Lane C's board_pins.yaml does not exist yet)
#         tools/gen_mps3_pins.py from feat/rm-ila-mint @ e54363022f
# Generated by Harness Manager (xdc export). Regenerate rather than edit: the
# checks that passed are listed in manifest.json next to this file.
##############################################################################

# bank 44: VCCO 1.8 V
set_property IOSTANDARD LVCMOS18 [get_ports rst_n]
set_property IOSTANDARD LVCMOS18 [get_ports {led_n[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_n[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_n[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_n[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_n[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_n[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_n[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_n[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sw[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sw[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sw[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sw[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sw[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sw[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sw[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {sw[0]}]

# bank 66: VCCO 1.8 V
set_property IOSTANDARD LVCMOS18 [get_ports clk]

# configuration bank voltage (a board fact)
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
