##############################################################################
# blinky_timing.xdc -- clocks
# design: blinky (a whole-FPGA blinky: the 50 MHz board clock, a reset button, 8 LEDs, 8 switches)
# board:  Arm V2M-MPS3 (HBI0309C), Kintex UltraScale KU115, part xcku115-flvb1760-1-c
# model:  DERIVED (harness Lane C's board_pins.yaml does not exist yet)
#         tools/gen_mps3_pins.py from feat/rm-ila-mint @ e54363022f
# Generated by Harness Manager (xdc export). Regenerate rather than edit: the
# checks that passed are listed in manifest.json next to this file.
# Board clocks only. The model has no board trace delays: add set_input_delay /
# set_output_delay for synchronous IO, or set_false_path for asynchronous IO
# (buttons, switches, LEDs).
##############################################################################

create_clock -name clk -period 20.000 -waveform {0.000 10.000} [get_ports clk]
