# The floorplan of lfsr_floor inside pblock_rp_dut (static 0x44EE76D5), written by
# hm_save_floorplan in build_rm.tcl. It is RM_XDC: read_xdc -cell u_rp_dut after the link
# makes each pblock u_rp_dut_<name>, a child of pblock_rp_dut. Names are relative to u_rp_dut.
create_pblock pblock_lfsr
resize_pblock [get_pblocks pblock_lfsr] -add {SLICE_X80Y90:SLICE_X87Y104}
add_cells_to_pblock [get_pblocks pblock_lfsr] [get_cells [list \
    {count_q[0]_i_2} \
    {count_q_reg[0]} \
    {count_q_reg[0]_i_1} \
    {count_q_reg[10]} \
    {count_q_reg[11]} \
    {count_q_reg[12]} \
    {count_q_reg[13]} \
    {count_q_reg[14]} \
    {count_q_reg[15]} \
    {count_q_reg[16]} \
    {count_q_reg[16]_i_1} \
    {count_q_reg[17]} \
    {count_q_reg[18]} \
    {count_q_reg[19]} \
    {count_q_reg[1]} \
    {count_q_reg[20]} \
    {count_q_reg[21]} \
    {count_q_reg[22]} \
    {count_q_reg[23]} \
    {count_q_reg[2]} \
    {count_q_reg[3]} \
    {count_q_reg[4]} \
    {count_q_reg[5]} \
    {count_q_reg[6]} \
    {count_q_reg[7]} \
    {count_q_reg[8]} \
    {count_q_reg[8]_i_1} \
    {count_q_reg[9]} \
    {gpio_i_q_reg[0]} \
    {gpio_i_q_reg[10]} \
    {gpio_i_q_reg[11]} \
    {gpio_i_q_reg[12]} \
    {gpio_i_q_reg[13]} \
    {gpio_i_q_reg[14]} \
    {gpio_i_q_reg[15]} \
    {gpio_i_q_reg[1]} \
    {gpio_i_q_reg[2]} \
    {gpio_i_q_reg[3]} \
    {gpio_i_q_reg[4]} \
    {gpio_i_q_reg[5]} \
    {gpio_i_q_reg[6]} \
    {gpio_i_q_reg[7]} \
    {gpio_i_q_reg[8]} \
    {gpio_i_q_reg[9]} \
    {gpio_q[0]_i_1} \
    {gpio_q[10]_i_1} \
    {gpio_q[11]_i_1} \
    {gpio_q[12]_i_1} \
    {gpio_q[13]_i_1} \
    {gpio_q[14]_i_1} \
    {gpio_q[15]_i_1} \
    {gpio_q[1]_i_1} \
    {gpio_q[2]_i_1} \
    {gpio_q[3]_i_1} \
    {gpio_q[4]_i_1} \
    {gpio_q[5]_i_1} \
    {gpio_q[6]_i_1} \
    {gpio_q[7]_i_1} \
    {gpio_q[8]_i_1} \
    {gpio_q[9]_i_1} \
    {gpio_q_reg[0]} \
    {gpio_q_reg[10]} \
    {gpio_q_reg[11]} \
    {gpio_q_reg[12]} \
    {gpio_q_reg[13]} \
    {gpio_q_reg[14]} \
    {gpio_q_reg[15]} \
    {gpio_q_reg[1]} \
    {gpio_q_reg[2]} \
    {gpio_q_reg[3]} \
    {gpio_q_reg[4]} \
    {gpio_q_reg[5]} \
    {gpio_q_reg[6]} \
    {gpio_q_reg[7]} \
    {gpio_q_reg[8]} \
    {gpio_q_reg[9]} \
    {irq_q_i_1} \
    {irq_q_i_2} \
    {irq_q_i_3} \
    {irq_q_i_4} \
    {irq_q_i_5} \
    {irq_q_i_6} \
    {irq_q_reg} \
    {lfsr_q[0]_i_1} \
    {lfsr_q[1]_i_1} \
    {lfsr_q[21]_i_1} \
    {lfsr_q_reg[0]} \
    {lfsr_q_reg[10]} \
    {lfsr_q_reg[11]} \
    {lfsr_q_reg[12]} \
    {lfsr_q_reg[13]} \
    {lfsr_q_reg[14]} \
    {lfsr_q_reg[15]} \
    {lfsr_q_reg[16]} \
    {lfsr_q_reg[17]} \
    {lfsr_q_reg[18]} \
    {lfsr_q_reg[19]} \
    {lfsr_q_reg[1]} \
    {lfsr_q_reg[20]} \
    {lfsr_q_reg[21]} \
    {lfsr_q_reg[22]} \
    {lfsr_q_reg[23]} \
    {lfsr_q_reg[24]} \
    {lfsr_q_reg[25]} \
    {lfsr_q_reg[26]} \
    {lfsr_q_reg[27]} \
    {lfsr_q_reg[28]} \
    {lfsr_q_reg[29]} \
    {lfsr_q_reg[2]} \
    {lfsr_q_reg[30]} \
    {lfsr_q_reg[31]} \
    {lfsr_q_reg[3]} \
    {lfsr_q_reg[4]} \
    {lfsr_q_reg[5]} \
    {lfsr_q_reg[6]} \
    {lfsr_q_reg[7]} \
    {lfsr_q_reg[8]} \
    {lfsr_q_reg[9]}]]
