
####################################################################################
# Generated by Vivado 2026.1 built on 'Tue Jun 16 11:01:26 MDT 2026' by 'xbuild'
# Command Used: write_xdc -cell u_rp_dut -force /tmpdir/claude-74755/kit-interactive/runs/a4/fp_cell.xdc
####################################################################################


####################################################################################
# Constraints from file : 'lfsr_floor_ooc.xdc'
####################################################################################

create_clock -period 20.000 -name dut_clk -waveform {0.000 10.000} [get_ports -scoped_to_current_instance dut_clk]
create_clock -period 80.000 -name dbg_bscan_tck -waveform {0.000 40.000} [get_ports -scoped_to_current_instance dbg_bscan_tck]
create_clock -period 80.000 -name dbg_bscan_drck -waveform {0.000 40.000} [get_ports -scoped_to_current_instance dbg_bscan_drck]
set_clock_groups -name async_lfsr_floor -asynchronous -group [get_clocks -of [get_ports dut_clk]] -group [list [get_clocks -of [get_ports dbg_bscan_tck]] [get_clocks -of [get_ports dbg_bscan_drck]]]

# User Generated physical constraints 

create_pblock pblock_rp_dut
add_cells_to_pblock [get_pblocks pblock_rp_dut] [get_cells -quiet [list \
          GND \
          GND_1 \
          HD_PR_Connection_Inserted_VCC_dbg_bscan_tdo \
          HD_PR_Connection_Inserted_VCC_dut_lockup \
          HD_PR_Connection_Inserted_VCC_jtag_tdo \
          HD_PR_Connection_Inserted_VCC_mdc \
          HD_PR_Connection_Inserted_VCC_mdio_o \
          HD_PR_Connection_Inserted_VCC_mdio_oe \
          HD_PR_Connection_Inserted_VCC_phy_rmii_tx_en \
          HD_PR_Connection_Inserted_VCC_phy_rmii_txd_0_ \
          HD_PR_Connection_Inserted_VCC_phy_rmii_txd_1_ \
          HD_PR_Connection_Inserted_VCC_qspi_io_o_0_ \
          HD_PR_Connection_Inserted_VCC_qspi_io_o_1_ \
          HD_PR_Connection_Inserted_VCC_qspi_io_o_2_ \
          HD_PR_Connection_Inserted_VCC_qspi_io_o_3_ \
          HD_PR_Connection_Inserted_VCC_qspi_io_oe_0_ \
          HD_PR_Connection_Inserted_VCC_qspi_io_oe_1_ \
          HD_PR_Connection_Inserted_VCC_qspi_io_oe_2_ \
          HD_PR_Connection_Inserted_VCC_qspi_io_oe_3_ \
          HD_PR_Connection_Inserted_VCC_qspi_sclk \
          HD_PR_Connection_Inserted_VCC_rm_id_0_ \
          HD_PR_Connection_Inserted_VCC_rm_id_10_ \
          HD_PR_Connection_Inserted_VCC_rm_id_14_ \
          HD_PR_Connection_Inserted_VCC_rm_id_16_ \
          HD_PR_Connection_Inserted_VCC_rm_id_17_ \
          HD_PR_Connection_Inserted_VCC_rm_id_18_ \
          HD_PR_Connection_Inserted_VCC_rm_id_19_ \
          HD_PR_Connection_Inserted_VCC_rm_id_20_ \
          HD_PR_Connection_Inserted_VCC_rm_id_21_ \
          HD_PR_Connection_Inserted_VCC_rm_id_22_ \
          HD_PR_Connection_Inserted_VCC_rm_id_23_ \
          HD_PR_Connection_Inserted_VCC_rm_id_25_ \
          HD_PR_Connection_Inserted_VCC_rm_id_26_ \
          HD_PR_Connection_Inserted_VCC_rm_id_27_ \
          HD_PR_Connection_Inserted_VCC_rm_id_28_ \
          HD_PR_Connection_Inserted_VCC_rm_id_29_ \
          HD_PR_Connection_Inserted_VCC_rm_id_30_ \
          HD_PR_Connection_Inserted_VCC_rm_id_31_ \
          HD_PR_Connection_Inserted_VCC_rm_id_3_ \
          HD_PR_Connection_Inserted_VCC_rm_id_4_ \
          HD_PR_Connection_Inserted_VCC_rm_id_5_ \
          HD_PR_Connection_Inserted_VCC_rm_id_8_ \
          HD_PR_Connection_Inserted_VCC_rm_id_9_ \
          HD_PR_Connection_Inserted_VCC_swo \
          HD_PR_Connection_Inserted_VCC_uart_rx_tready \
          HD_PR_Connection_Inserted_VCC_uart_tx_tdata_0_ \
          HD_PR_Connection_Inserted_VCC_uart_tx_tdata_1_ \
          HD_PR_Connection_Inserted_VCC_uart_tx_tdata_2_ \
          HD_PR_Connection_Inserted_VCC_uart_tx_tdata_3_ \
          HD_PR_Connection_Inserted_VCC_uart_tx_tdata_4_ \
          HD_PR_Connection_Inserted_VCC_uart_tx_tdata_5_ \
          HD_PR_Connection_Inserted_VCC_uart_tx_tdata_6_ \
          HD_PR_Connection_Inserted_VCC_uart_tx_tdata_7_ \
          HD_PR_Connection_Inserted_VCC_uart_tx_tvalid \
          VCC]]
resize_pblock [get_pblocks pblock_rp_dut] -add {SLICE_X48Y0:SLICE_X95Y119 \
                                                DSP48E2_X9Y0:DSP48E2_X17Y47 \
                                                RAMB18_X6Y0:RAMB18_X11Y47 \
                                                RAMB36_X6Y0:RAMB36_X11Y23 \
}
set_property CONTAIN_ROUTING 1 [get_pblocks pblock_rp_dut]
set_property EXCLUDE_PLACEMENT 1 [get_pblocks pblock_rp_dut]
set_property SNAPPING_MODE ON [get_pblocks pblock_rp_dut]

# User Generated miscellaneous constraints 

set_property HD.RECONFIGURABLE true [current_design]

# User Generated physical constraints 

create_pblock pblock_lfsr
set_property PARENT pblock_rp_dut [get_pblocks pblock_lfsr]
add_cells_to_pblock [get_pblocks pblock_lfsr] [get_cells -quiet [list \
          GND_HD_Inserted_Inst_dbg_bscan_tdo \
          GND_HD_Inserted_Inst_dut_lockup \
          GND_HD_Inserted_Inst_jtag_tdo \
          GND_HD_Inserted_Inst_mdc \
          GND_HD_Inserted_Inst_mdio_o \
          GND_HD_Inserted_Inst_mdio_oe \
          GND_HD_Inserted_Inst_phy_rmii_tx_en \
          GND_HD_Inserted_Inst_phy_rmii_txd_0_ \
          GND_HD_Inserted_Inst_phy_rmii_txd_1_ \
          GND_HD_Inserted_Inst_qspi_io_o_0_ \
          GND_HD_Inserted_Inst_qspi_io_o_1_ \
          GND_HD_Inserted_Inst_qspi_io_o_2_ \
          GND_HD_Inserted_Inst_qspi_io_o_3_ \
          GND_HD_Inserted_Inst_qspi_io_oe_0_ \
          GND_HD_Inserted_Inst_qspi_io_oe_1_ \
          GND_HD_Inserted_Inst_qspi_io_oe_2_ \
          GND_HD_Inserted_Inst_qspi_io_oe_3_ \
          GND_HD_Inserted_Inst_qspi_sclk \
          GND_HD_Inserted_Inst_rm_id_0_ \
          GND_HD_Inserted_Inst_rm_id_10_ \
          GND_HD_Inserted_Inst_rm_id_14_ \
          GND_HD_Inserted_Inst_rm_id_16_ \
          GND_HD_Inserted_Inst_rm_id_17_ \
          GND_HD_Inserted_Inst_rm_id_18_ \
          GND_HD_Inserted_Inst_rm_id_19_ \
          GND_HD_Inserted_Inst_rm_id_20_ \
          GND_HD_Inserted_Inst_rm_id_21_ \
          GND_HD_Inserted_Inst_rm_id_22_ \
          GND_HD_Inserted_Inst_rm_id_23_ \
          GND_HD_Inserted_Inst_rm_id_25_ \
          GND_HD_Inserted_Inst_rm_id_26_ \
          GND_HD_Inserted_Inst_rm_id_27_ \
          GND_HD_Inserted_Inst_rm_id_28_ \
          GND_HD_Inserted_Inst_rm_id_29_ \
          GND_HD_Inserted_Inst_rm_id_30_ \
          GND_HD_Inserted_Inst_rm_id_31_ \
          GND_HD_Inserted_Inst_rm_id_3_ \
          GND_HD_Inserted_Inst_rm_id_4_ \
          GND_HD_Inserted_Inst_rm_id_5_ \
          GND_HD_Inserted_Inst_rm_id_8_ \
          GND_HD_Inserted_Inst_rm_id_9_ \
          GND_HD_Inserted_Inst_swo \
          GND_HD_Inserted_Inst_uart_rx_tready \
          GND_HD_Inserted_Inst_uart_tx_tdata_0_ \
          GND_HD_Inserted_Inst_uart_tx_tdata_1_ \
          GND_HD_Inserted_Inst_uart_tx_tdata_2_ \
          GND_HD_Inserted_Inst_uart_tx_tdata_3_ \
          GND_HD_Inserted_Inst_uart_tx_tdata_4_ \
          GND_HD_Inserted_Inst_uart_tx_tdata_5_ \
          GND_HD_Inserted_Inst_uart_tx_tdata_6_ \
          GND_HD_Inserted_Inst_uart_tx_tdata_7_ \
          GND_HD_Inserted_Inst_uart_tx_tvalid \
          VCC_HD_Inserted_Inst_dut_gpio_oe_0_ \
          VCC_HD_Inserted_Inst_dut_gpio_oe_10_ \
          VCC_HD_Inserted_Inst_dut_gpio_oe_11_ \
          VCC_HD_Inserted_Inst_dut_gpio_oe_12_ \
          VCC_HD_Inserted_Inst_dut_gpio_oe_13_ \
          VCC_HD_Inserted_Inst_dut_gpio_oe_14_ \
          VCC_HD_Inserted_Inst_dut_gpio_oe_15_ \
          VCC_HD_Inserted_Inst_dut_gpio_oe_1_ \
          VCC_HD_Inserted_Inst_dut_gpio_oe_2_ \
          VCC_HD_Inserted_Inst_dut_gpio_oe_3_ \
          VCC_HD_Inserted_Inst_dut_gpio_oe_4_ \
          VCC_HD_Inserted_Inst_dut_gpio_oe_5_ \
          VCC_HD_Inserted_Inst_dut_gpio_oe_6_ \
          VCC_HD_Inserted_Inst_dut_gpio_oe_7_ \
          VCC_HD_Inserted_Inst_dut_gpio_oe_8_ \
          VCC_HD_Inserted_Inst_dut_gpio_oe_9_ \
          VCC_HD_Inserted_Inst_qspi_csn \
          VCC_HD_Inserted_Inst_rm_id_11_ \
          VCC_HD_Inserted_Inst_rm_id_12_ \
          VCC_HD_Inserted_Inst_rm_id_13_ \
          VCC_HD_Inserted_Inst_rm_id_15_ \
          VCC_HD_Inserted_Inst_rm_id_1_ \
          VCC_HD_Inserted_Inst_rm_id_24_ \
          VCC_HD_Inserted_Inst_rm_id_2_ \
          VCC_HD_Inserted_Inst_rm_id_6_ \
          VCC_HD_Inserted_Inst_rm_id_7_ \
          {count_q[0]_i_2} \
          {count_q_reg[0]} \
          {count_q_reg[0]_i_1} \
          {count_q_reg[10]} \
          {count_q_reg[11]} \
          {count_q_reg[12]} \
          {count_q_reg[13]} \
          {count_q_reg[14]} \
          {count_q_reg[15]} \
          {count_q_reg[16]} \
          {count_q_reg[16]_i_1} \
          {count_q_reg[17]} \
          {count_q_reg[18]} \
          {count_q_reg[19]} \
          {count_q_reg[1]} \
          {count_q_reg[20]} \
          {count_q_reg[21]} \
          {count_q_reg[22]} \
          {count_q_reg[23]} \
          {count_q_reg[2]} \
          {count_q_reg[3]} \
          {count_q_reg[4]} \
          {count_q_reg[5]} \
          {count_q_reg[6]} \
          {count_q_reg[7]} \
          {count_q_reg[8]} \
          {count_q_reg[8]_i_1} \
          {count_q_reg[9]} \
          {gpio_i_q_reg[0]} \
          {gpio_i_q_reg[10]} \
          {gpio_i_q_reg[11]} \
          {gpio_i_q_reg[12]} \
          {gpio_i_q_reg[13]} \
          {gpio_i_q_reg[14]} \
          {gpio_i_q_reg[15]} \
          {gpio_i_q_reg[1]} \
          {gpio_i_q_reg[2]} \
          {gpio_i_q_reg[3]} \
          {gpio_i_q_reg[4]} \
          {gpio_i_q_reg[5]} \
          {gpio_i_q_reg[6]} \
          {gpio_i_q_reg[7]} \
          {gpio_i_q_reg[8]} \
          {gpio_i_q_reg[9]} \
          {gpio_q[0]_i_1} \
          {gpio_q[10]_i_1} \
          {gpio_q[11]_i_1} \
          {gpio_q[12]_i_1} \
          {gpio_q[13]_i_1} \
          {gpio_q[14]_i_1} \
          {gpio_q[15]_i_1} \
          {gpio_q[1]_i_1} \
          {gpio_q[2]_i_1} \
          {gpio_q[3]_i_1} \
          {gpio_q[4]_i_1} \
          {gpio_q[5]_i_1} \
          {gpio_q[6]_i_1} \
          {gpio_q[7]_i_1} \
          {gpio_q[8]_i_1} \
          {gpio_q[9]_i_1} \
          {gpio_q_reg[0]} \
          {gpio_q_reg[10]} \
          {gpio_q_reg[11]} \
          {gpio_q_reg[12]} \
          {gpio_q_reg[13]} \
          {gpio_q_reg[14]} \
          {gpio_q_reg[15]} \
          {gpio_q_reg[1]} \
          {gpio_q_reg[2]} \
          {gpio_q_reg[3]} \
          {gpio_q_reg[4]} \
          {gpio_q_reg[5]} \
          {gpio_q_reg[6]} \
          {gpio_q_reg[7]} \
          {gpio_q_reg[8]} \
          {gpio_q_reg[9]} \
          irq_q_i_1 \
          irq_q_i_2 \
          irq_q_i_3 \
          irq_q_i_4 \
          irq_q_i_5 \
          irq_q_i_6 \
          irq_q_reg \
          {lfsr_q[0]_i_1} \
          {lfsr_q[1]_i_1} \
          {lfsr_q[21]_i_1} \
          {lfsr_q_reg[0]} \
          {lfsr_q_reg[10]} \
          {lfsr_q_reg[11]} \
          {lfsr_q_reg[12]} \
          {lfsr_q_reg[13]} \
          {lfsr_q_reg[14]} \
          {lfsr_q_reg[15]} \
          {lfsr_q_reg[16]} \
          {lfsr_q_reg[17]} \
          {lfsr_q_reg[18]} \
          {lfsr_q_reg[19]} \
          {lfsr_q_reg[1]} \
          {lfsr_q_reg[20]} \
          {lfsr_q_reg[21]} \
          {lfsr_q_reg[22]} \
          {lfsr_q_reg[23]} \
          {lfsr_q_reg[24]} \
          {lfsr_q_reg[25]} \
          {lfsr_q_reg[26]} \
          {lfsr_q_reg[27]} \
          {lfsr_q_reg[28]} \
          {lfsr_q_reg[29]} \
          {lfsr_q_reg[2]} \
          {lfsr_q_reg[30]} \
          {lfsr_q_reg[31]} \
          {lfsr_q_reg[3]} \
          {lfsr_q_reg[4]} \
          {lfsr_q_reg[5]} \
          {lfsr_q_reg[6]} \
          {lfsr_q_reg[7]} \
          {lfsr_q_reg[8]} \
          {lfsr_q_reg[9]}]]
resize_pblock [get_pblocks pblock_lfsr] -add {SLICE_X80Y90:SLICE_X87Y104}
set_property SNAPPING_MODE NESTED [get_pblocks pblock_lfsr]
