##############################################################################
# minimal_ooc.xdc -- out-of-context timing for an RM of static 0x44EE76D5
# design: minimal (the smallest RM: clock, resets and rm_id; every other group tied off (fpga/rp/_template))
# board:  Arm V2M-MPS3 (HBI0309C), Kintex UltraScale KU115, part xcku115-flvb1760-1-c
# model:  DERIVED (harness Lane C's board_pins.yaml does not exist yet)
#         tools/gen_mps3_pins.py from feat/rm-ila-mint @ e54363022f
# Generated by Harness Manager (xdc export). Regenerate rather than edit: the
# checks that passed are listed in manifest.json next to this file.
# OOC ONLY: read with read_xdc after synth_design in your OOC run. At the DFX
# link the static's propagated clocks supersede every create_clock here.
# No Tcl control flow (read_xdc rejects it); -quiet on every port query so a
# tied-off port that synthesis removed is not an error.
##############################################################################

# --- clocks the shell drives across the boundary (partition-timing contract) ---
# dut_clk: static: clk_out1_shell_bd_clk_wiz_dut_0
create_clock -name dut_clk -period 20.000 -waveform {0.000 10.000} [get_ports dut_clk]
# dbg_bscan_tck: static: debug_bridge_0 soft-BSCAN TCK (generated, static BUFGCE)
create_clock -name dbg_bscan_tck -period 80.000 -waveform {0.000 40.000} [get_ports dbg_bscan_tck]
# dbg_bscan_drck: OOC-only; no static counterpart
create_clock -name dbg_bscan_drck -period 80.000 -waveform {0.000 40.000} [get_ports dbg_bscan_drck]
# the static's clock buffer that drives dut_clk into the partition
set_property -quiet HD.CLK_SRC BUFGCE_X2Y47 [get_ports -quiet dut_clk]

# --- every boundary clock is asynchronous to the others (the static owns the CDC) ---
set_clock_groups -name async_minimal -asynchronous \
    -group [get_clocks -quiet -include_generated_clocks dut_clk] \
    -group [get_clocks -quiet -include_generated_clocks {dbg_bscan_tck dbg_bscan_drck}]

# --- boundary false paths: every crossing is CDC'd on the static side ---
# clkrst (used)
set_false_path -quiet -from [get_ports -quiet {dut_resetn rp_resetn dbg_resetn}]
# jtag (tied off)
set_false_path -quiet -from [get_ports -quiet {jtag_tck jtag_tms jtag_tdi}]
set_false_path -quiet -to   [get_ports -quiet jtag_tdo]
# dbgbscan (tied off)
set_false_path -quiet -from [get_ports -quiet {dbg_bscan_bscanid_en dbg_bscan_capture dbg_bscan_reset dbg_bscan_runtest dbg_bscan_sel dbg_bscan_shift dbg_bscan_tdi dbg_bscan_tms dbg_bscan_update}]
set_false_path -quiet -to   [get_ports -quiet dbg_bscan_tdo]
# eth (tied off)
set_false_path -quiet -from [get_ports -quiet {phy_rmii_ref_clk phy_rmii_crs_dv phy_rmii_rxd[*] mdio_i}]
set_false_path -quiet -to   [get_ports -quiet {phy_rmii_txd[*] phy_rmii_tx_en mdc mdio_o mdio_oe}]
# uart (tied off)
set_false_path -quiet -from [get_ports -quiet {uart_tx_tready uart_rx_tdata[*] uart_rx_tvalid}]
set_false_path -quiet -to   [get_ports -quiet {uart_tx_tdata[*] uart_tx_tvalid uart_rx_tready swo}]
# status (used)
set_false_path -quiet -to   [get_ports -quiet {rm_id[*] dut_lockup irq_out}]
# gpio (tied off)
set_false_path -quiet -from [get_ports -quiet {dut_gpio_i[*]}]
set_false_path -quiet -to   [get_ports -quiet {dut_gpio_o[*] dut_gpio_oe[*]}]
# qspi (tied off)
set_false_path -quiet -from [get_ports -quiet {qspi_io_i[*]}]
set_false_path -quiet -to   [get_ports -quiet {qspi_sclk qspi_csn qspi_io_o[*] qspi_io_oe[*]}]
