"""The front panel's wire vocabulary, generated for the Python code and the web UI (PANEL-V017).

A Linux harness frame (net-protocol v0.17, ``{"op":"panel","frame":"a"|"b"}``) gives each
cell a role CODE, ``chr(ord("a") + i)`` for the i-th role of ``design/tokens.json``
``panel.roles`` (the order ``tools/gen_tokens.py`` gives ``clcd_palette.h``'s enum), and a
status glyph as the byte 0x80-0x86 (``\\u0080``-``\\u0086`` on the wire), drawn from the
panel's glyph table. Harness Manager decodes both in two places, Python
(``harness_manager.core.panel``) and the web UI's text mirror (``sections/panel.js``), so
this script writes ONE vocabulary into both, from the one source of each:

- ``src/harness_manager/core/panel_codes.py``;
- ``src/harness_manager/web/static/js/panel_codes.js``.

Each holds the roles in the tokens' order, each role's colours as the glass shows them
(RGB565, ``design/generated/palette.json``'s ``fg_shown``/``bg_shown``), and the glyphs
(code, name, 16 scanlines, bit 7 the leftmost pixel) from ``tools/clcd_mock.py``'s
``GLYPHS`` (FIX-PACK-2 moves that table into ``tools/gen_tokens.py`` as ``CLCD_GLYPHS``
and leaves ``clcd_mock.GLYPHS`` the same object, so this reads it either way). A glyph's
one-column stand-in for a terminal is the status grammar's ASCII fallback when that is one
character, else ``*``.

``--check`` fails when an output is stale or missing (``tests/unit/test_panel_v017.py`` runs
it, so ``make check`` does). Usage::

    python3 tools/gen_panel_codes.py            # write the outputs that changed
    python3 tools/gen_panel_codes.py --check    # exit 1 and say why when one drifted

Stdlib only; Python 3.10+.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PY_OUT = Path("src/harness_manager/core/panel_codes.py")
JS_OUT = Path("src/harness_manager/web/static/js/panel_codes.js")
REGENERATE = "run: python3 tools/gen_panel_codes.py"
#: The stand-in for a glyph the status grammar gives no one-character ASCII for.
STAND_IN_DEFAULT = "*"


def _tool(name: str, root: Path):
    """``tools/<name>.py`` loaded by path (the tools are scripts, not a package)."""
    key = name if root == ROOT else f"{name}@{root}"
    if key not in sys.modules:
        spec = importlib.util.spec_from_file_location(key, root / "tools" / f"{name}.py")
        mod = importlib.util.module_from_spec(spec)
        sys.modules[key] = mod
        spec.loader.exec_module(mod)
    return sys.modules[key]


def vocabulary(root: Path = ROOT) -> dict:
    """``{sha, roles: [(name, fg, bg)], glyphs: [(code, name, rows, stand_in)]}``."""
    gt = _tool("gen_tokens", ROOT)                 # the generator's code; the data is root's
    # R2: the panel's frozen tokens (design/panel/tokens.json), never the web's theme
    tokens, raw = gt.load_panel(root)
    roles = [(name, r["fg_shown"], r["bg_shown"]) for name, r in gt.panel_roles(tokens).items()]
    grammar = tokens.get("grammar") or {}
    ascii_of = {spec.get("glyph"): str(spec.get("ascii") or "") for spec in grammar.values()}
    glyphs = []
    for name, (ch, rows) in _tool("clcd_mock", ROOT).GLYPHS.items():
        text = ascii_of.get(name, "")
        glyphs.append((ord(ch), name, [int(v) & 0xFF for v in rows],
                       text if len(text) == 1 else STAND_IN_DEFAULT))
    glyphs.sort()
    return {"sha": gt.sha256_of(raw), "roles": roles, "glyphs": glyphs,
            "theme": tokens["panel"]["theme"]}


HEADER = ("GENERATED by tools/gen_panel_codes.py from design/tokens.json (panel.roles, grammar) "
          "and the panel's glyph table (tools/clcd_mock.py GLYPHS): do not edit. Change the "
          "source, then " + REGENERATE + ".")


def render_py(v: dict) -> str:
    lines = [
        '"""The front panel\'s wire vocabulary: role codes and status glyphs (PANEL-V017).',
        "",
        *_wrap(HEADER, 92),
        "",
        'A frame\'s role code for ``ROLES[i]`` is ``chr(ord("a") + i)`` (net-protocol v0.17); a',
        "glyph is the character ``chr(code)``. ``harness_manager.core.panel`` decodes with these;",
        "the web UI's ``js/panel_codes.js`` holds the same, from the same generator.",
        '"""',
        "",
        f'TOKENS_SHA256 = "{v["sha"]}"',
        "#: The panel's theme in the tokens (the colours below are that theme's).",
        f'PANEL_THEME = "{v["theme"]}"',
        "",
        "#: The colour roles, in design/tokens.json order (= clcd_palette.h's enum clcd_role).",
        "ROLES: tuple[str, ...] = (",
        *[f'    "{name}",' for name, _fg, _bg in v["roles"]],
        ")",
        "",
        "#: role -> (fg, bg) as the glass shows them (RGB565, expanded).",
        "ROLE_COLOURS: dict[str, tuple[str, str]] = {",
        *[f'    "{name}": ("{fg}", "{bg}"),' for name, fg, bg in v["roles"]],
        "}",
        "",
        "#: The status glyphs: code -> (name, 16 scanlines with bit 7 the leftmost pixel,",
        "#: a one-column stand-in for a terminal).",
        "GLYPHS: dict[int, tuple[str, tuple[int, ...], str]] = {",
        *[f'    0x{code:02X}: ("{name}", ({", ".join(f"0x{b:02X}" for b in rows)}), '
          f"{json.dumps(stand)})," for code, name, rows, stand in v["glyphs"]],
        "}",
    ]
    return "\n".join(lines) + "\n"


def render_js(v: dict) -> str:
    lines = [
        "// The front panel's wire vocabulary: role codes and status glyphs (PANEL-V017).",
        "//",
        *[f"// {chunk}" for chunk in _wrap(HEADER, 96)],
        "//",
        '// A frame\'s role code for ROLES[i] is String.fromCharCode(97 + i) (net-protocol v0.17);',
        "// a glyph is the character with that code. core/panel_codes.py holds the same.",
        "",
        f'export const TOKENS_SHA256 = "{v["sha"]}";',
        f'export const PANEL_THEME = "{v["theme"]}";',
        "",
        "// The colour roles, in design/tokens.json order (= clcd_palette.h's enum clcd_role).",
        "export const ROLES = [",
        *[f'  "{name}",' for name, _fg, _bg in v["roles"]],
        "];",
        "",
        "// role -> [fg, bg] as the glass shows them (RGB565, expanded).",
        "export const ROLE_COLOURS = {",
        *[f'  "{name}": ["{fg}", "{bg}"],' for name, fg, bg in v["roles"]],
        "};",
        "",
        "// The status glyphs: code -> {name, rows: 16 scanlines, bit 7 the leftmost pixel, standIn}.",
        "export const GLYPHS = {",
        *[f'  {code}: {{ name: "{name}", rows: [{", ".join(str(b) for b in rows)}], '
          f"standIn: {json.dumps(stand)} }}," for code, name, rows, stand in v["glyphs"]],
        "};",
    ]
    return "\n".join(lines) + "\n"


def _wrap(text: str, width: int) -> list[str]:
    out, cur = [], ""
    for word in text.split():
        if cur and len(cur) + 1 + len(word) > width:
            out.append(cur)
            cur = word
        else:
            cur = f"{cur} {word}" if cur else word
    return [*out, cur] if cur else out


def outputs(root: Path = ROOT) -> dict[Path, str]:
    v = vocabulary(root)
    return {PY_OUT: render_py(v), JS_OUT: render_js(v)}


def _text(path: Path) -> str:
    return path.read_bytes().decode("utf-8").replace("\r\n", "\n")


def check(root: Path = ROOT) -> list[str]:
    """Every output that drifted from its sources (empty when none did)."""
    try:
        want = outputs(root)
    except (OSError, ValueError) as exc:
        return [str(exc)]
    problems = []
    for rel, text in want.items():
        path = root / rel
        if not path.is_file():
            problems.append(f"{rel.as_posix()} is missing: {REGENERATE}")
        elif _text(path) != text:
            problems.append(f"{rel.as_posix()} is stale (it does not match design/tokens.json "
                            f"and the glyph table): {REGENERATE}")
    return problems


def write(root: Path = ROOT) -> list[Path]:
    written = []
    for rel, text in outputs(root).items():
        path = root / rel
        if path.is_file() and _text(path) == text:
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
        written.append(rel)
    return written


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="write nothing; exit 1 if stale")
    ap.add_argument("--root", type=Path, default=ROOT, help="the checkout (default: this one)")
    a = ap.parse_args(argv)
    root = a.root.resolve()
    if a.check:
        problems = check(root)
        for p in problems:
            print(f"gen_panel_codes: {p}", file=sys.stderr)
        if problems:
            return 1
        print("gen_panel_codes: ok")
        return 0
    for rel in write(root):
        print(f"wrote {rel.as_posix()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
