"""The lcd_mirror wire as Harness Manager reads it (docs/design/LCD_MIRROR.md §6.1; lane LM1).

The authority is the board's own bytes: ``tests/fixtures/lcdmirror_wire/`` (the Linux
lead's wire vectors, platform ``feat/lcd-mirror`` d86ce81, generated by the encoders
``mps3-lcdmirror`` sends with). Every vector is parsed and checked against the board's
``manifest.json`` (CRC-32s of the SOURCE pixels, so the decoder is judged on the picture),
and HM's encoder must rebuild each one byte for byte (the fake board speaks the board's
exact bytes). Hand-built payloads remain only as negative twins (a plausible misreading
must NOT give the picture). A corrupted vector must fail the checksum or the parse.
"""

from __future__ import annotations

import hashlib
import json
import os
import random
import struct
import zlib
from pathlib import Path
from typing import Any

import pytest

from harness_manager.core import display as D
from harness_manager.core import display_wire as w

VECTORS = Path(__file__).resolve().parents[1] / "fixtures" / "lcdmirror_wire"
MANIFEST = json.loads((VECTORS / "manifest.json").read_text())
ENTRIES = {e["file"]: e for e in MANIFEST["vectors"]}
UPDATES = [e for e in MANIFEST["vectors"] if e["kind"] == "update"]
KEYFRAME = next(e for e in MANIFEST["vectors"] if e["kind"] == "keyframe")
REFUSALS = [e["file"] for e in MANIFEST["vectors"] if e["kind"] == "refusal"]
TEXT_ONLY_SW = w.ST_RST_N | w.ST_BL | w.ST_DISPLAY_ON | w.ST_FMT_OK | w.S_TEXT_ONLY


def vector(name: str) -> bytes:
    return (VECTORS / name).read_bytes()


def sha256sums() -> dict[str, str]:
    out = {}
    for line in (VECTORS / "SHA256SUMS").read_text().splitlines():
        digest, name = line.split()
        out[name] = digest
    return out


def read_one(data: bytes, max_msg: int = w.MAX_MSG_DEFAULT) -> Any:
    got = w.MessageReader(max_msg).feed(data)
    assert len(got) == 1
    return got[0]


# --- the fixtures are the board's, unchanged ----------------------------------------------------


def test_every_fixture_file_matches_its_checksum() -> None:
    sums = sha256sums()
    files = sorted(p.name for p in VECTORS.iterdir() if p.name not in ("SHA256SUMS", "README.md", ".gitignore"))
    assert sorted(sums) == files
    for name in files:
        assert hashlib.sha256(vector(name)).hexdigest() == sums[name], name


def test_the_manifest_covers_every_encoding_a_split_keyframe_and_both_refusals() -> None:
    assert sorted(e["tiles"][0][1] for e in UPDATES) == [w.E_FILL, w.E_PAL1, w.E_PAL2, w.E_RLE16, w.E_RAW]
    assert len(KEYFRAME["parts"]) == 3 and KEYFRAME["valid_count"] == 300
    assert len(REFUSALS) == 2 and "hello.bin" in ENTRIES


# --- HELLO ---------------------------------------------------------------------------------------


def test_hello_vector() -> None:
    info = read_one(vector("hello.bin"))
    assert isinstance(info, w.DisplayInfo)
    assert (info.proto, info.w, info.h, info.fmt, info.tile) == (1, 320, 240, "rgb565le", 16)
    assert (info.mode, info.static_id, info.max_msg) == ("sw", "0x5a5a0001", 65536)
    assert info.extra == {"boot_id": "00000000-0000-0000-0000-000000000000", "rate": 5,
                          "rate_max": 30, "clients_max": 2}
    assert info.supported() == ""


@pytest.mark.parametrize("patch, words", [
    ({"proto": 2}, "proto 2"), ({"w": 480}, "480x240"), ({"fmt": "rgb565be"}, "rgb565be"),
    ({"mode": "xx"}, "mode 'xx'"), ({"max_msg": 1024}, "max_msg 1024"),
    ({"max_msg": 131072}, "max_msg 131072")])
def test_hello_this_hm_cannot_render_says_why(patch: dict, words: str) -> None:
    info = read_one(vector("hello.bin"))
    obj = {**info.to_json(), **patch}
    patched = w.parse_hello(json.dumps(obj).encode())
    assert words in patched.supported()


def test_hello_that_is_not_json() -> None:
    with pytest.raises(w.WireError):
        w.parse_hello(b"not json")
    with pytest.raises(w.WireError):
        w.parse_hello(b"[1,2]")


# --- one UPDATE per encoding -------------------------------------------------------------------


@pytest.mark.parametrize("entry", UPDATES, ids=[e["file"] for e in UPDATES])
def test_update_vector_decodes_to_the_manifest(entry: dict) -> None:
    u = read_one(vector(entry["file"]))
    assert isinstance(u, w.DisplayUpdate)
    assert (u.seq, u.t_ms, u.status, u.owner) == (entry["seq"], entry["t_ms"], entry["status"], entry["owner"])
    assert u.status == TEXT_ONLY_SW | w.S_SNAP_LAST                   # a sw-mode harness screen
    assert u.flags.text_only and u.snap_last and not u.key and not u.flags.exact
    assert (u.frames, u.resets) == (77, 1)
    assert u.regs is None and u.mode_regs() == w.ModeRegs(0x00, 0x09, 0x05, 0x20)
    assert w.valid_tiles(u.valid) == set(range(300))
    ((idx, enc, ln, crc),) = entry["tiles"]
    (rec,) = u.tiles
    assert (rec.idx, rec.enc, len(rec.payload)) == (idx, enc, ln)
    assert zlib.crc32(w.decode_tile(rec.enc, rec.payload)) == crc


@pytest.mark.parametrize("entry", UPDATES, ids=[e["file"] for e in UPDATES])
def test_hm_rebuilds_each_update_vector_byte_for_byte(entry: dict) -> None:
    """The fake board (and so every HM test) speaks the board's exact bytes: HM's encoder
    picks the same encoding and payload, and its builder the same message."""
    raw = vector(entry["file"])
    u = read_one(raw)
    (rec,) = u.tiles
    tile = w.decode_tile(rec.enc, rec.payload)
    assert w.encode_tile(tile) == (rec.enc, rec.payload)
    again = w.update_msg(u.seq, u.t_ms, u.frames, u.resets, u.status, u.owner, u.valid,
                         [w.record(rec.idx, *w.encode_tile(tile))], mode=u.mode)
    assert again == raw


# --- the split keyframe ------------------------------------------------------------------------


def keyframe_parts() -> list[bytes]:
    return [vector(p) for p in KEYFRAME["parts"]]


def test_split_keyframe_vector_is_the_frame() -> None:
    reader = w.MessageReader()
    ups = [m for part in keyframe_parts() for m in reader.feed(part)]
    assert [u.seq for u in ups] == [KEYFRAME["seq_first"] + i for i in range(3)]
    assert [(u.key, u.key_first, u.key_last, u.snap_last) for u in ups] == [
        (True, True, False, False), (True, False, False, False), (True, False, True, True)]
    assert ups[0].regs is not None and ups[1].regs is None and ups[1].mode == 0x00090520
    assert len({(u.t_ms, u.frames, u.resets, u.status & ~w.S_FRAMING, u.valid) for u in ups}) == 1
    assert all(len(p) <= 65536 for p in keyframe_parts())         # max_msg counts the header
    f = D.DisplayFrame()
    f.commit(ups, D.decode_parts(ups), key=True)
    assert 300 - f.hatched() == KEYFRAME["valid_count"]
    assert zlib.crc32(f.rgb565()) == KEYFRAME["frame_crc"]
    assert sum(len(u.tiles) for u in ups) == 300 and {r.enc for u in ups for r in u.tiles} == {w.E_RAW}


def test_hm_splits_the_keyframe_exactly_as_the_board_does() -> None:
    reader = w.MessageReader()
    ups = [m for part in keyframe_parts() for m in reader.feed(part)]
    f = D.DisplayFrame()
    f.commit(ups, D.decode_parts(ups), key=True)
    recs = w.encode_records(f.rgb565(), range(300))
    parts = w.split_records(recs, w.part_budget(w.MAX_MSG_DEFAULT, True))
    first = ups[0]
    rebuilt = []
    for i, chunk in enumerate(parts):
        flags = w.S_KEY | (w.S_KEY_FIRST if i == 0 else 0) | \
            ((w.S_KEY_LAST | w.S_SNAP_LAST) if i == len(parts) - 1 else 0)
        rebuilt.append(w.update_msg(first.seq + i, first.t_ms, first.frames, first.resets,
                                    (first.status & ~w.S_FRAMING) | flags, first.owner, first.valid,
                                    chunk, regs=first.regs, mode=ups[1].mode))
    assert rebuilt == keyframe_parts()


# --- refusals ----------------------------------------------------------------------------------


@pytest.mark.parametrize("name, err", [("refusal_busy.txt", "lcd_mirror: busy (2 clients)"),
                                       ("refusal_not_loopback.txt",
                                        "lcd_mirror: not loopback (use an ssh port forward)")])
def test_refusal_vectors(name: str, err: str) -> None:
    line = vector(name)
    assert line == w.refusal_line(err)                           # the fake refuses in these bytes
    r = w.MessageReader()
    assert r.feed(line[:10]) == []
    (ref,) = r.feed(line[10:] + vector("update_fill.bin"))
    assert isinstance(ref, w.Refusal) and ref.err == err
    assert r.done and r.feed(vector("update_fill.bin")) == []


def test_refusal_cut_short_by_the_close() -> None:
    r = w.MessageReader()
    assert r.feed(vector("refusal_busy.txt")[:34]) == []
    ref = r.eof()
    assert isinstance(ref, w.Refusal) and "lcd_mirror: bu" in ref.err


# --- negative twin: a corrupted vector must fail the checksum or the parse -----------------------


def _judge(name: str, data: bytes) -> str:
    """'ok' when ``data`` still decodes to what the manifest says; else why not."""
    if hashlib.sha256(data).hexdigest() != sha256sums()[name]:
        checksum = "checksum"
    else:
        checksum = ""
    try:
        if name.startswith("key_split_"):
            parts = [data if p == name else vector(p) for p in KEYFRAME["parts"]]
            reader = w.MessageReader()
            ups = [m for part in parts for m in reader.feed(part)]
            f = D.DisplayFrame()
            f.commit(ups, D.decode_parts(ups), key=True)
            good = zlib.crc32(f.rgb565()) == KEYFRAME["frame_crc"] and \
                [u.seq for u in ups] == [KEYFRAME["seq_first"] + i for i in range(3)]
        elif name.startswith("update_"):
            e = ENTRIES[name]
            u = read_one(data)
            ((idx, enc, ln, crc),) = e["tiles"]
            (rec,) = u.tiles
            good = (u.seq, u.t_ms, u.status, u.owner) == (e["seq"], e["t_ms"], e["status"], e["owner"]) \
                and (rec.idx, rec.enc, len(rec.payload)) == (idx, enc, ln) \
                and zlib.crc32(w.decode_tile(rec.enc, rec.payload)) == crc \
                and w.valid_tiles(u.valid) == set(range(300))
        elif name == "hello.bin":
            info = read_one(data)
            good = info == read_one(vector("hello.bin"))
        else:
            ref = read_one(data)
            good = ref == read_one(vector(name))
    except (w.WireError, ValueError, struct.error, AssertionError):
        return "parse" + (f"+{checksum}" if checksum else "")
    if not good:
        return "manifest" + (f"+{checksum}" if checksum else "")
    return checksum or "ok"


CORRUPTIONS = [(name, spot) for name in sorted(sha256sums()) if name != "manifest.json"
               for spot in ("magic", "length", "middle", "last")]


@pytest.mark.parametrize("name, spot", CORRUPTIONS, ids=[f"{n}-{s}" for n, s in CORRUPTIONS])
def test_negative_twin_a_corrupted_vector_is_caught(name: str, spot: str) -> None:
    data = bytearray(vector(name))
    assert _judge(name, bytes(data)) == "ok"                      # the twin's control
    i = {"magic": 0, "length": 4, "middle": len(data) // 2, "last": len(data) - 2}[spot]
    data[i] ^= 0x5A
    assert _judge(name, bytes(data)) in ("parse+checksum", "manifest+checksum")


def test_negative_twin_a_one_bit_pixel_flip_passes_the_parse_but_not_the_manifest() -> None:
    """The subtle case: a flipped pixel bit is a well-formed message. Only the manifest's
    CRC of the source pixels catches it, which is why the vectors carry it."""
    data = bytearray(vector("update_raw.bin"))
    data[-1] ^= 0x01
    u = read_one(bytes(data))                                    # parses cleanly
    assert _judge("update_raw.bin", bytes(data)) == "manifest+checksum"
    assert zlib.crc32(w.decode_tile(u.tiles[0].enc, u.tiles[0].payload)) != ENTRIES["update_raw.bin"]["tiles"][0][3]


# --- framing and client messages ---------------------------------------------------------------
# No vectors exist for the client's side: these are net-protocol.md v0.15's table, literally.


def test_client_messages_are_the_literal_bytes() -> None:
    assert w.key_msg() == bytes.fromhex("4c4d1000" "00000000")
    assert w.rate_msg(20) == bytes.fromhex("4c4d1100" "01000000" "14")
    assert w.rate_msg(999) == bytes.fromhex("4c4d1100" "01000000" "ff")       # a u8
    assert w.ping_msg(7) == bytes.fromhex("4c4d1200" "04000000" "07000000")
    assert w.ack_msg(0x01020304) == bytes.fromhex("4c4d1400" "04000000" "04030201")   # H1


def test_valid_map_is_lsb_first() -> None:
    b = w.valid_bytes({0, 9, 299})
    assert len(b) == 38
    assert b[0] == 0x01 and b[1] == 0x02 and b[37] == 0x08
    assert w.valid_tiles(b) == {0, 9, 299}
    assert w.valid_tiles(w.ALL_VALID) == set(range(300))
    assert read_one(vector("update_fill.bin")).valid == w.ALL_VALID   # the board's all-300 map
    with pytest.raises(w.WireError):
        w.valid_bytes({300})


def test_mode_word_layout() -> None:
    regs = bytearray(256)
    regs[0x01], regs[0x36], regs[0x17], regs[0x16] = 0x11, 0x09, 0x05, 0x20
    assert w.mode_word(regs) == 0x11090520
    assert w.mode_regs(0x11090520) == w.ModeRegs(0x11, 0x09, 0x05, 0x20)
    assert read_one(vector("update_fill.bin")).mode == 0x00090520     # R16 | R17<<8 | R36<<16


def test_key_first_carries_regs_not_the_mode_word() -> None:
    regs = bytes(range(256))
    status = w.S_KEY | w.S_KEY_FIRST | w.S_KEY_LAST | w.S_SNAP_LAST
    body = w.update_body(9, 0, 0, 0, status, 1, w.ALL_VALID, [], regs=regs)
    assert len(body) == 59 + 256 + 2
    u = w.parse_update(body)
    assert u.regs == regs and u.mode is None and u.key and u.key_first and u.key_last and u.snap_last
    assert u.owner == w.OWNER_DUT
    with pytest.raises(w.WireError):
        w.update_body(9, 0, 0, 0, status, 1, w.ALL_VALID, [])      # key_first without REGS


def test_status_bits() -> None:
    f = w.StatusFlags(w.ST_RST_N | w.ST_BL | w.ST_DISPLAY_ON | w.ST_FMT_OK | w.ST_VIOL | w.S_BLIND
                      | w.S_TEXT_ONLY | w.S_SNAP_LAST)
    assert f.rst_n and f.bl and f.display_on and f.fmt_ok and f.viol and f.blind and f.text_only
    assert not (f.standby or f.approx or f.exact or f.oob or f.rd_seen or f.owner_dut or f.key)
    assert f.snap_last
    j = f.to_json()
    assert j["viol"] is True and j["exact"] is False
    assert j["word"] == f"0x{(f.word & ~w.S_FRAMING):08x}"
    assert (w.ST_VIOL, w.S_EXACT, w.S_TEXT_ONLY, w.S_BLIND) == (1 << 8, 1 << 16, 1 << 17, 1 << 18)
    assert (w.S_KEY, w.S_KEY_FIRST, w.S_KEY_LAST, w.S_SNAP_LAST) == (1 << 24, 1 << 25, 1 << 26, 1 << 27)


def test_owner_names() -> None:
    assert [w.owner_name(o) for o in (0, 1, 2, 3, 200)] == ["harness", "dut", "unknown", "unknown", "unknown"]


# --- the reader ------------------------------------------------------------------------------------


def test_reader_takes_the_board_stream_byte_by_byte() -> None:
    stream = vector("hello.bin") + b"".join(keyframe_parts()) + vector("update_pal2.bin") \
        + w.pong_msg(5) + w.message(w.T_RATE, b"\x1e") + w.message(0x7F, b"future")
    r = w.MessageReader()
    got = []
    step = 997                                                    # odd-sized reads across headers
    for i in range(0, len(stream), step):
        got += r.feed(stream[i:i + step])
    assert [type(m).__name__ for m in got] == ["DisplayInfo"] + ["DisplayUpdate"] * 4 + \
        ["Pong", "RateEcho", "Unknown"]
    assert got[5] == w.Pong(5) and got[6] == w.RateEcho(30) and got[7] == w.Unknown(0x7F, b"future")
    assert r.pending == 0 and r.bytes == len(stream)


def test_reader_refuses_what_is_not_the_wire() -> None:
    with pytest.raises(w.WireError):
        w.MessageReader().feed(b"SSH-2.0-dropbear\r\n")
    with pytest.raises(w.WireError):                             # max_msg counts the header (H3)
        w.MessageReader(max_msg=65536).feed(w.HEADER.pack(b"LM", w.T_UPDATE, 0, 65536 - 7))
    w.MessageReader(max_msg=65536).feed(w.HEADER.pack(b"LM", w.T_UPDATE, 0, 65536 - 8))


@pytest.mark.parametrize("cut", ["short", "trailing", "idx", "enc", "ntiles", "record"])
def test_malformed_updates_are_refused(cut: str) -> None:
    body = bytearray(vector("update_fill.bin")[8:])
    if cut == "short":
        body = body[:40]
    elif cut == "trailing":
        body += b"\x00"
    elif cut == "idx":
        body[-7:-5] = struct.pack("<H", 300)
    elif cut == "enc":
        body[-5] = 5
    elif cut == "ntiles":
        body[-9:-7] = struct.pack("<H", 301)
    elif cut == "record":
        body[-4:-2] = struct.pack("<H", 9)
    with pytest.raises(w.WireError):
        w.parse_update(bytes(body))


# --- the five encodings: hand-built payloads -----------------------------------------------------


def px(*values: int) -> bytes:
    return struct.pack(f"<{len(values)}H", *values)


def test_pal1_bit_x_selects_colour_1_lsb_first() -> None:
    c0, c1 = 0x0000, 0xFFFF
    rows = [1 << y for y in range(16)]                     # the diagonal
    payload = struct.pack("<2H16H", c0, c1, *rows)
    assert payload[4:6] == b"\x01\x00"                     # row 0: only pixel 0 set
    tile = w.decode_tile(w.E_PAL1, payload)
    want = b"".join(px(*(c1 if x == y else c0 for x in range(16))) for y in range(16))
    assert tile == want


def test_pal1_negative_twin_msb_first_is_caught() -> None:
    """The same payload read MSB first (a plausible misreading) must NOT give the picture."""
    payload = struct.pack("<2H16H", 0, 0xFFFF, *[1 << y for y in range(16)])
    tile = w.decode_tile(w.E_PAL1, payload)
    msb = b"".join(px(*(0xFFFF if x == 15 - y else 0 for x in range(16))) for y in range(16))
    assert tile != msb


def test_pal2_pixel_x_is_bits_2x_plus_1_to_2x() -> None:
    pal = (0x0001, 0x0002, 0x0003, 0x0004)
    rows = [sum(((x + y) % 4) << (2 * x) for x in range(16)) for y in range(16)]
    payload = struct.pack("<4H16I", *pal, *rows)
    assert payload[8:12] == struct.pack("<I", 0xE4E4E4E4)      # row 0: 0,1,2,3,0,1,...
    tile = w.decode_tile(w.E_PAL2, payload)
    assert tile == b"".join(px(*(pal[(x + y) % 4] for x in range(16))) for y in range(16))


def test_rle16_runs_and_literals() -> None:
    payload = bytes([0x80 | 127]) + px(0xAAAA) + bytes([0x80 | 125]) + px(0xBBBB) \
        + bytes([0x02]) + px(1, 2, 3)                      # 128 + 126 + 3 = 257: one too many
    with pytest.raises(w.WireError):
        w.decode_tile(w.E_RLE16, payload)
    payload = bytes([0x80 | 127]) + px(0xAAAA) + bytes([0x80 | 124]) + px(0xBBBB) \
        + bytes([0x02]) + px(1, 2, 3)                      # 128 + 125 + 3 = 256
    assert w.decode_tile(w.E_RLE16, payload) == px(0xAAAA) * 128 + px(0xBBBB) * 125 + px(1, 2, 3)


@pytest.mark.parametrize("enc, payload", [
    (w.E_FILL, b"\x00\x00\x00"), (w.E_RAW, bytes(510)), (w.E_PAL1, bytes(35)), (w.E_PAL2, bytes(73)),
    (w.E_RLE16, bytes([0x80 | 127])), (w.E_RLE16, bytes([0x05]) + px(1, 2)), (w.E_RLE16, b""),
    (5, bytes(2))])
def test_malformed_tiles_are_refused(enc: int, payload: bytes) -> None:
    with pytest.raises(w.WireError):
        w.decode_tile(enc, payload)


def test_rgb565_is_little_endian_negative_twin() -> None:
    """Amendment 1: LE. A big-endian reading of the same FILL must not give the colour."""
    tile = w.decode_tile(w.E_FILL, b"\x00\xf8")             # 0xF800 = red, LE
    assert struct.unpack_from("<H", tile)[0] == 0xF800
    assert struct.unpack_from(">H", tile)[0] != 0xF800


# --- the encoder (the fake board's) against the decoder ------------------------------------------


def _tiles(seed: int) -> list[bytes]:
    rnd = random.Random(seed)
    out = [px(0x1234) * 256, os.urandom(512)]
    for ncol in (2, 3, 4, 5, 8):
        pal = [rnd.randrange(65536) for _ in range(ncol)]
        out.append(px(*(rnd.choice(pal) for _ in range(256))))
        out.append(px(*(pal[(i // 37) % ncol] for i in range(256))))      # runs
    out.append(px(*range(256)))                                          # a gradient
    return out


@pytest.mark.parametrize("seed", range(4))
def test_every_encoding_round_trips(seed: int) -> None:
    seen = set()
    for tile in _tiles(seed):
        enc, payload = w.encode_tile(tile)
        seen.add(enc)
        assert w.decode_tile(enc, payload) == tile
        size = {w.E_FILL: 2, w.E_PAL1: 36, w.E_PAL2: 72, w.E_RAW: 512}.get(enc)
        assert size is None or len(payload) == size
    assert seen >= {w.E_FILL, w.E_RAW, w.E_RLE16}


def test_encoder_picks_the_smallest() -> None:
    two = px(*((0xFFFF if (x + y) % 2 else 0) for y in range(16) for x in range(16)))
    assert w.encode_tile(two)[0] == w.E_PAL1                 # RLE would be 512+
    four = px(*((x % 4) * 0x1111 for y in range(16) for x in range(16)))
    assert w.encode_tile(four)[0] == w.E_PAL2
    runs = px(*([7] * 128 + [9] * 128))
    assert w.encode_tile(runs) == (w.E_RLE16, bytes([0xFF]) + px(7) + bytes([0xFF]) + px(9))


def test_split_records_respects_max_msg() -> None:
    frame = os.urandom(w.FRAME_BYTES)
    recs = w.encode_records(frame, range(300))
    for key in (True, False):
        parts = w.split_records(recs, w.part_budget(65536, key))
        assert len(parts) >= 3 and sum(len(p) for p in parts) == 300
        for i, p in enumerate(parts):
            status = (w.S_KEY_FIRST if key and i == 0 else 0)
            m = w.update_msg(i, 0, 0, 0, status, 0, w.ALL_VALID, p, regs=bytes(256), mode=0)
            assert len(m) <= 65536                            # H3: max_msg counts the header
    assert w.split_records([], 100) == [[]]


def test_frame_tile_helpers_invert() -> None:
    frame = bytearray(os.urandom(w.FRAME_BYTES))
    t = 21                                                   # tx 1, ty 1
    assert w.tile_origin(t) == (16, 16)
    tile = w.tile_of_frame(frame, t)
    assert tile[:32] == bytes(frame[(16 * 320 + 16) * 2:(16 * 320 + 32) * 2])
    other = bytearray(w.FRAME_BYTES)
    w.put_tile_in_frame(other, t, tile)
    assert w.tile_of_frame(other, t) == tile
